## Лабораторная работа №1
### Выполнила студентка 4 курса группы БВТ2002
### Леонова Виктория Олеговна

In [1]:
import numpy as np

def Convolution2D(input, weight, bias=None, stride=1, padding=0):

    # Получение размеров входного изображения и фильтра
    input_height, input_width = input.shape
    filter_height, filter_width = weight.shape

    # Расчет размеров выходного изображения
    output_height = (input_height - filter_height + 2 * padding) // stride + 1
    output_width = (input_width - filter_width + 2 * padding) // stride + 1

    # Добавление отступов к входному изображению
    if padding > 0:
        padded_input = np.pad(input, padding, mode='constant')
    else:
        padded_input = input

    # Создание выходного массива
    output = np.zeros((output_height, output_width))

    # Проход по выходным пикселям
    for i in range(output_height):
        for j in range(output_width):

            # Вычисление значения свертки для текущего пикселя
            output[i, j] = np.sum(padded_input[i:i+filter_height, j:j+filter_width] * weight)

            # Добавление смещения (bias), если указано
            if bias is not None:
                output[i, j] += bias

    return output

In [2]:
# Входные данные
input = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Фильтр
weight = np.array([[1, 0, -1],
                   [2, 0, -2],
                   [1, 0, -1]])

# Вызов функции свертки
output = Convolution2D(input, weight, stride=1, padding=1)

In [3]:
# Вывод результата
print(output)

[[ -9.  -6.   9.]
 [-20.  -8.  20.]
 [-21.  -6.  21.]]


In [4]:
#Тест 1: свертка с фильтром 3x3 без отступов и смещения
def test_1():
  input_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
  weight_1 = np.array([[1, 0, -1],
                   [2, 0, -2],
                   [1, 0, -1]])
  expected_output_1 = np.array([[-9, -6, 9],
                              [-20, -8, 20],
                              [-21, -6, 21]])
  output_1 = Convolution2D(input_1, weight_1, stride=1, padding=1)
  assert np.array_equal(output_1, expected_output_1), "Пройден"

In [5]:
test_1()